// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: order/proto/order/order.proto

/*
Package go_micro_srv_order is a generated protocol buffer package.

It is generated from these files:
	order/proto/order/order.proto

It has these top-level messages:
	SubmitRequest
	Response
	OrderDetailRequest
*/
package go_micro_srv_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderService interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...client.CallOption) (*Response, error)
	OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...client.CallOption) (*Response, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.order"
	}
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) Submit(ctx context.Context, in *SubmitRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OrderService.Submit", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OrderService.OrderDetail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	Submit(context.Context, *SubmitRequest, *Response) error
	OrderDetail(context.Context, *OrderDetailRequest, *Response) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) error {
	type orderService interface {
		Submit(ctx context.Context, in *SubmitRequest, out *Response) error
		OrderDetail(ctx context.Context, in *OrderDetailRequest, out *Response) error
	}
	type OrderService struct {
		orderService
	}
	h := &orderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderService{h}, opts...))
}

type orderServiceHandler struct {
	OrderServiceHandler
}

func (h *orderServiceHandler) Submit(ctx context.Context, in *SubmitRequest, out *Response) error {
	return h.OrderServiceHandler.Submit(ctx, in, out)
}

func (h *orderServiceHandler) OrderDetail(ctx context.Context, in *OrderDetailRequest, out *Response) error {
	return h.OrderServiceHandler.OrderDetail(ctx, in, out)
}
