// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/proto/order/order.proto

package go_micro_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitRequest struct {
	ProductId            uint32   `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Uid                  uint32   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d04744a214c910fc, []int{0}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetProductId() uint32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *SubmitRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SubmitRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d04744a214c910fc, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type OrderDetailRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailRequest) Reset()         { *m = OrderDetailRequest{} }
func (m *OrderDetailRequest) String() string { return proto.CompactTextString(m) }
func (*OrderDetailRequest) ProtoMessage()    {}
func (*OrderDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d04744a214c910fc, []int{2}
}

func (m *OrderDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailRequest.Unmarshal(m, b)
}
func (m *OrderDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailRequest.Marshal(b, m, deterministic)
}
func (m *OrderDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailRequest.Merge(m, src)
}
func (m *OrderDetailRequest) XXX_Size() int {
	return xxx_messageInfo_OrderDetailRequest.Size(m)
}
func (m *OrderDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailRequest proto.InternalMessageInfo

func (m *OrderDetailRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*SubmitRequest)(nil), "go.micro.srv.order.SubmitRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.order.Response")
	proto.RegisterType((*OrderDetailRequest)(nil), "go.micro.srv.order.OrderDetailRequest")
}

func init() { proto.RegisterFile("order/proto/order/order.proto", fileDescriptor_d04744a214c910fc) }

var fileDescriptor_d04744a214c910fc = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x5d, 0xab, 0xd5, 0x1d, 0x2d, 0xc8, 0xe0, 0x61, 0x91, 0x0a, 0x9a, 0x83, 0x78, 0x4a,
	0x45, 0x5f, 0xc1, 0x8b, 0x78, 0x10, 0x52, 0xfa, 0x00, 0x36, 0x19, 0x4a, 0xc0, 0xed, 0xac, 0xf9,
	0xd3, 0x07, 0xf3, 0x09, 0x25, 0xb3, 0x2e, 0x2a, 0x2d, 0xf4, 0x12, 0xbe, 0xf9, 0xf7, 0xf1, 0xfb,
	0x08, 0x5c, 0x73, 0x70, 0x14, 0x66, 0x5d, 0xe0, 0xc4, 0xb3, 0x5e, 0xcb, 0xab, 0xa5, 0x83, 0xb8,
	0x62, 0xdd, 0x7a, 0x1b, 0x58, 0xc7, 0xb0, 0xd1, 0x32, 0x51, 0x0b, 0x98, 0xcc, 0xf3, 0xb2, 0xf5,
	0xc9, 0xd0, 0x67, 0xa6, 0x98, 0x70, 0x0a, 0x75, 0x17, 0xd8, 0x65, 0x9b, 0x5e, 0x5c, 0x53, 0xdd,
	0x54, 0xf7, 0x13, 0xf3, 0xdb, 0xc0, 0x4b, 0x38, 0xb6, 0x9c, 0xd7, 0xa9, 0x39, 0x94, 0x49, 0x5f,
	0xe0, 0x05, 0x8c, 0xb2, 0x77, 0xcd, 0x48, 0x7a, 0x45, 0xaa, 0x07, 0x38, 0x35, 0x14, 0x3b, 0x5e,
	0x47, 0x42, 0x84, 0x23, 0xcb, 0x8e, 0xc4, 0xac, 0x36, 0xa2, 0xcb, 0x45, 0x1b, 0x57, 0xe2, 0x52,
	0x9b, 0x22, 0x95, 0x06, 0x7c, 0x2b, 0x44, 0xcf, 0x94, 0xde, 0xfd, 0xc7, 0x40, 0xd3, 0xc0, 0x89,
	0x70, 0xfe, 0xb0, 0xd4, 0x66, 0x28, 0x1f, 0xbf, 0x2a, 0x38, 0x97, 0x83, 0x39, 0x85, 0x8d, 0xb7,
	0x84, 0xaf, 0x30, 0xee, 0x93, 0xe0, 0xad, 0xde, 0x0e, 0xaa, 0xff, 0xa5, 0xbc, 0x9a, 0xee, 0x5a,
	0x19, 0x88, 0xd5, 0x01, 0x2e, 0xe0, 0xec, 0x0f, 0x0d, 0xde, 0xed, 0x5a, 0xdf, 0xc6, 0xdd, 0x67,
	0xbb, 0x1c, 0xcb, 0x47, 0x3c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xea, 0x7f, 0xdf, 0xb0, 0xa9,
	0x01, 0x00, 0x00,
}
