// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification/proto/notification/notification.proto

package go_micro_srv_notification

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	product "product/proto/product"
	user "user/proto/user"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyOrderRequest struct {
	User                 *user.User       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Product              *product.Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NotifyOrderRequest) Reset()         { *m = NotifyOrderRequest{} }
func (m *NotifyOrderRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyOrderRequest) ProtoMessage()    {}
func (*NotifyOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1bb7ece923756e, []int{0}
}

func (m *NotifyOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyOrderRequest.Unmarshal(m, b)
}
func (m *NotifyOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyOrderRequest.Marshal(b, m, deterministic)
}
func (m *NotifyOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyOrderRequest.Merge(m, src)
}
func (m *NotifyOrderRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyOrderRequest.Size(m)
}
func (m *NotifyOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyOrderRequest proto.InternalMessageInfo

func (m *NotifyOrderRequest) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *NotifyOrderRequest) GetProduct() *product.Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type SubmitRequest struct {
	ProductId            uint32   `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Uid                  uint32   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1bb7ece923756e, []int{1}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetProductId() uint32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *SubmitRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SubmitRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1bb7ece923756e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*NotifyOrderRequest)(nil), "go.micro.srv.notification.NotifyOrderRequest")
	proto.RegisterType((*SubmitRequest)(nil), "go.micro.srv.notification.SubmitRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.notification.Response")
}

func init() {
	proto.RegisterFile("notification/proto/notification/notification.proto", fileDescriptor_ea1bb7ece923756e)
}

var fileDescriptor_ea1bb7ece923756e = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xb5, 0xb6, 0x7e, 0x64, 0x4a, 0x44, 0x16, 0xc1, 0x18, 0x14, 0x24, 0xbd, 0x08, 0xe2, 0x56,
	0xe2, 0xc1, 0xdf, 0xe0, 0x45, 0x65, 0x4b, 0x7f, 0x80, 0xdd, 0xac, 0x65, 0x0f, 0xc9, 0xc4, 0xfd,
	0x28, 0xe8, 0xaf, 0x97, 0x9d, 0x6c, 0x30, 0x41, 0xf4, 0xb2, 0xfb, 0x66, 0xe6, 0xcd, 0x7b, 0xc3,
	0x0c, 0x94, 0x0d, 0x3a, 0xfd, 0xae, 0xe5, 0x9b, 0xd3, 0xd8, 0x2c, 0x5b, 0x83, 0x0e, 0x97, 0xa3,
	0xd4, 0x30, 0xe0, 0x54, 0x67, 0x17, 0x5b, 0xe4, 0xb5, 0x96, 0x06, 0xb9, 0x35, 0x3b, 0x3e, 0x24,
	0xe4, 0xb9, 0xb7, 0xca, 0x44, 0x19, 0x82, 0xe1, 0xe9, 0xda, 0xf2, 0x45, 0x6b, 0xb0, 0xf2, 0xd2,
	0xc5, 0xf2, 0x20, 0x0a, 0x7f, 0x47, 0x2a, 0xbe, 0x80, 0x3d, 0x07, 0xc1, 0xcf, 0x17, 0x53, 0x29,
	0x23, 0xd4, 0x87, 0x57, 0xd6, 0xb1, 0x5b, 0x98, 0x05, 0xa1, 0x6c, 0x72, 0x3d, 0xb9, 0x99, 0x97,
	0xe7, 0x7c, 0x34, 0x00, 0x59, 0xac, 0xad, 0x32, 0x82, 0x48, 0xec, 0x11, 0x8e, 0xa2, 0x66, 0xb6,
	0x4f, 0xfc, 0xab, 0x31, 0xbf, 0x37, 0x7c, 0xed, 0x7e, 0xd1, 0xb3, 0x8b, 0x35, 0xa4, 0x2b, 0xbf,
	0xa9, 0xb5, 0xeb, 0x6d, 0x2f, 0x21, 0x89, 0xb5, 0xa7, 0x8a, 0xbc, 0x53, 0xf1, 0x93, 0x60, 0x67,
	0x70, 0x20, 0xd1, 0x37, 0x9d, 0x4b, 0x2a, 0xba, 0x80, 0x9d, 0xc2, 0xd4, 0xeb, 0x2a, 0x9b, 0x52,
	0x2e, 0xc0, 0xe2, 0x1e, 0x8e, 0x85, 0xb2, 0x2d, 0x36, 0x56, 0x31, 0x06, 0x33, 0x89, 0x95, 0x22,
	0xb1, 0x44, 0x10, 0x0e, 0x1d, 0xb5, 0xdd, 0x92, 0x4a, 0x22, 0x02, 0x2c, 0x3d, 0x9c, 0xc4, 0xe1,
	0x56, 0xca, 0xec, 0xb4, 0x54, 0x4c, 0xc2, 0x7c, 0xb0, 0x16, 0x76, 0xc7, 0xff, 0x3c, 0x01, 0xff,
	0xbd, 0xbe, 0x7c, 0xf1, 0x0f, 0xbd, 0x1f, 0xad, 0xd8, 0xdb, 0x1c, 0xd2, 0x09, 0x1e, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xee, 0xdc, 0x92, 0x28, 0x14, 0x02, 0x00, 0x00,
}
