// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product/notification.proto

/*
Package go_micro_srv_product is a generated protocol buffer package.

It is generated from these files:
	product/notification.proto

It has these top-level messages:
	Product
	SearchRequest
	DetailRequest
	ReduceNumberRequest
	Response
	SearchResponse
	DetailResponse
*/
package go_micro_srv_product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductService service

type ProductService interface {
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Detail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error)
	ReduceNumber(ctx context.Context, in *ReduceNumberRequest, opts ...client.CallOption) (*Response, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.product"
	}
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) Detail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Detail", in)
	out := new(DetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) ReduceNumber(ctx context.Context, in *ReduceNumberRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ProductService.ReduceNumber", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Detail(context.Context, *DetailRequest, *DetailResponse) error
	ReduceNumber(context.Context, *ReduceNumberRequest, *Response) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) error {
	type productService interface {
		Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error
		Detail(ctx context.Context, in *DetailRequest, out *DetailResponse) error
		ReduceNumber(ctx context.Context, in *ReduceNumberRequest, out *Response) error
	}
	type ProductService struct {
		productService
	}
	h := &productServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductService{h}, opts...))
}

type productServiceHandler struct {
	ProductServiceHandler
}

func (h *productServiceHandler) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.ProductServiceHandler.Search(ctx, in, out)
}

func (h *productServiceHandler) Detail(ctx context.Context, in *DetailRequest, out *DetailResponse) error {
	return h.ProductServiceHandler.Detail(ctx, in, out)
}

func (h *productServiceHandler) ReduceNumber(ctx context.Context, in *ReduceNumberRequest, out *Response) error {
	return h.ProductServiceHandler.ReduceNumber(ctx, in, out)
}
