// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product/notification.proto

package go_micro_srv_product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Intro                string   `protobuf:"bytes,3,opt,name=intro,proto3" json:"intro,omitempty"`
	Number               uint32   `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *Product) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DetailRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{2}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReduceNumberRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceNumberRequest) Reset()         { *m = ReduceNumberRequest{} }
func (m *ReduceNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ReduceNumberRequest) ProtoMessage()    {}
func (*ReduceNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{3}
}

func (m *ReduceNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceNumberRequest.Unmarshal(m, b)
}
func (m *ReduceNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceNumberRequest.Marshal(b, m, deterministic)
}
func (m *ReduceNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceNumberRequest.Merge(m, src)
}
func (m *ReduceNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ReduceNumberRequest.Size(m)
}
func (m *ReduceNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceNumberRequest proto.InternalMessageInfo

func (m *ReduceNumberRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SearchResponse struct {
	Code                 string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Products             []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{5}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SearchResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SearchResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type DetailResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{6}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DetailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DetailResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "go.micro.srv.product.Product")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.product.SearchRequest")
	proto.RegisterType((*DetailRequest)(nil), "go.micro.srv.product.DetailRequest")
	proto.RegisterType((*ReduceNumberRequest)(nil), "go.micro.srv.product.ReduceNumberRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.product.Response")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.product.SearchResponse")
	proto.RegisterType((*DetailResponse)(nil), "go.micro.srv.product.DetailResponse")
}

func init() { proto.RegisterFile("product/notification.proto", fileDescriptor_5f9f5dc4dd6fa6d7) }

var fileDescriptor_5f9f5dc4dd6fa6d7 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x0b, 0xd4, 0xb6, 0x8e, 0x96, 0x98, 0xb1, 0x1a, 0xd2, 0x44, 0x6d, 0xb6, 0x9a, 0xd4,
	0x0b, 0x9a, 0x7a, 0x30, 0xde, 0x3d, 0x1b, 0x43, 0xe3, 0xa9, 0xa7, 0x16, 0x26, 0x75, 0x13, 0x61,
	0xdb, 0x5d, 0xe8, 0x9f, 0xf1, 0xcf, 0x1a, 0x96, 0xa5, 0x8a, 0x01, 0x4d, 0x4f, 0xcc, 0x2e, 0x6f,
	0xbf, 0xd9, 0xf7, 0x06, 0xe0, 0x6c, 0x2d, 0x45, 0x94, 0x85, 0xe9, 0x9d, 0x79, 0xfa, 0x6b, 0x29,
	0x52, 0x81, 0x83, 0x95, 0xf0, 0x63, 0x1e, 0x4a, 0xe1, 0x2b, 0xb9, 0xf5, 0xcd, 0x3b, 0x36, 0x87,
	0xee, 0x6b, 0x51, 0xa2, 0x0b, 0x36, 0x8f, 0x3c, 0x6b, 0x64, 0x4d, 0xfa, 0x81, 0xcd, 0x23, 0x44,
	0x68, 0x27, 0x8b, 0x98, 0x3c, 0x7b, 0x64, 0x4d, 0x0e, 0x03, 0x5d, 0xe3, 0x00, 0x0e, 0x78, 0x92,
	0x4a, 0xe1, 0x39, 0x7a, 0xb3, 0x58, 0xe0, 0x39, 0x74, 0x92, 0x2c, 0x5e, 0x92, 0xf4, 0xda, 0xfa,
	0xb4, 0x59, 0xb1, 0x31, 0xf4, 0x67, 0xb4, 0x90, 0xe1, 0x7b, 0x40, 0x9b, 0x8c, 0x54, 0xba, 0x43,
	0x5a, 0xdf, 0x48, 0x76, 0x05, 0xfd, 0x67, 0x4a, 0x17, 0xfc, 0xa3, 0x14, 0xfd, 0xba, 0x07, 0xbb,
	0x81, 0xd3, 0x80, 0xa2, 0x2c, 0xa4, 0x17, 0x4d, 0x6d, 0x92, 0xdd, 0x43, 0x2f, 0x20, 0xb5, 0x16,
	0x89, 0xa2, 0xbc, 0x4f, 0x28, 0xa2, 0x5d, 0x9f, 0xbc, 0xc6, 0x13, 0x70, 0x62, 0xb5, 0x32, 0x6e,
	0xf2, 0x92, 0x6d, 0xc0, 0x2d, 0xaf, 0xb7, 0xcf, 0x39, 0x7c, 0x82, 0x9e, 0x89, 0x4f, 0x79, 0xce,
	0xc8, 0x99, 0x1c, 0x4d, 0x2f, 0xfc, 0xba, 0x70, 0x7d, 0x93, 0x6c, 0xb0, 0x93, 0x33, 0x01, 0x6e,
	0x69, 0x76, 0xaf, 0x96, 0x8f, 0xd0, 0x35, 0x0c, 0x9d, 0xfc, 0xbf, 0x1d, 0x4b, 0xf5, 0xf4, 0xd3,
	0x06, 0xd7, 0x6c, 0xce, 0x48, 0x6e, 0x79, 0x48, 0xf8, 0x06, 0x9d, 0xc2, 0x36, 0x8e, 0xeb, 0x21,
	0x95, 0x99, 0x0d, 0xaf, 0xff, 0x16, 0x15, 0x36, 0x58, 0x2b, 0xc7, 0x16, 0xd6, 0x9a, 0xb0, 0x95,
	0x29, 0x37, 0x61, 0xab, 0xe9, 0xb0, 0x16, 0xce, 0xe1, 0xf8, 0xe7, 0xf4, 0xf1, 0xb6, 0xfe, 0x5c,
	0xcd, 0x17, 0x32, 0xbc, 0x6c, 0x92, 0x96, 0xf0, 0x65, 0x47, 0xff, 0x1a, 0x0f, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x88, 0x3a, 0xaf, 0xc8, 0x33, 0x03, 0x00, 0x00,
}
